name: Deploy docs

on:
  push:
    branches:
      - 'demo'
    paths:
      - 'docs/**'
  repository_dispatch:
    types: deploy-docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
      - uses: actions/checkout@v2
        with:
          ref: demo
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "github-covhub@risav.dev"
          git config --global user.name "Github Covhub Action"
          npm run docs:serve